# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish AMS Wrapper

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    env:
      commitmsg: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        # settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}

    - name: Get current version from pom.xml file
      id: pom-version
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.github_token }}

    - name: Print the version
      run: "echo 'New Version: ${{steps.pom-version.outputs.version}}'" 

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Create GitHub Release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        # tag_name: ${{github.run_number}}
        # release_name: Release ${{github.run_number}}
        tag_name: ${{ steps.pom-version.outputs.version }}
        release_name: ${{ steps.pom-version.outputs.version }} 
        body: |
            $commitmsg
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url}}
        asset_path: ./target/alipay-ams-payments-${{ steps.pom-version.outputs.version }}.jar
        # asset_name: alipay-ams-payments-v${{ github.run_number}}.jar
        asset_name: alipay-ams-payments-${{ steps.pom-version.outputs.version }}.jar 
        asset_content_type: application/java-archive
        
        
